dist: trusty
sudo: required
language: cpp

matrix:
  include:
  - os: osx
      compiler: clang
      env:
        - CXX_COMPILER='clang++'
        - C_COMPILER='clang'
        - BUILD_TYPE='Release'
script:
  - mkdir Release
  - cd Release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
