dist: trusty
sudo: required
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-9.3']
      env: COMPILER=g++-9.3
    - os: osx
      compiler: clang
      env:
        - CXX_COMPILER='clang++'
        - C_COMPILER='clang'
      
script:
  - mkdir Release
  - cd Release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
